"use client";

import "maplibre-gl/dist/maplibre-gl.css";
import maplibregl from "maplibre-gl";
import { useEffect, useRef, useState } from "react";
import { fishingDetailItems, terrainDetailItems } from "@/domain/spotDetailUiPresentation";
import { createSpotFieldObservationDraft, getTodayInJapan, spotFieldObservationConfigs, type SpotFieldObservationDraft } from "@/domain/spotFieldObservation";
import { buildUserSpotDetailInput, userFishingSpotDetailItemKeys, userFishingSpotTypes, type UserFishingSpot, type UserFishingSpotDetailItemKey } from "@/domain/userFishingSpot";
import { createMyUserFishingSpotWithDetails } from "@/lib/userFishingSpotRepository";
import styles from "./UserFishingSpotRegistrationModal.module.css";
import { requestCurrentLocation, type CurrentLocation } from "@/domain/geolocation";

const fishingKeys = userFishingSpotDetailItemKeys.slice(0, 7);
const terrainKeys = userFishingSpotDetailItemKeys.slice(7);
const labels = new Map([...fishingDetailItems, ...terrainDetailItems]);
const initialDrafts = () => Object.fromEntries(userFishingSpotDetailItemKeys.map((key) => [key, createSpotFieldObservationDraft()])) as Record<UserFishingSpotDetailItemKey, SpotFieldObservationDraft>;

export function UserFishingSpotRegistrationModal({ initialLongitude, initialLatitude, onCurrentLocationChange = () => undefined, onClose, onCreated }: { initialLongitude: number; initialLatitude: number; currentLocation?: CurrentLocation | null; onCurrentLocationChange?: (location: CurrentLocation) => void; onClose: () => void; onCreated: (spot: UserFishingSpot) => void }) {
  const [name,setName]=useState(""); const [areaName,setAreaName]=useState(""); const [spotType,setSpotType]=useState("");
  const [latitude,setLatitude]=useState(String(initialLatitude)); const [longitude,setLongitude]=useState(String(initialLongitude));
  const [drafts,setDrafts]=useState(initialDrafts); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState<string|null>(null);
  const [locationPending,setLocationPending]=useState(false); const [locationMessage,setLocationMessage]=useState<string|null>(null);
  const creationId=useRef(crypto.randomUUID());
  const mapNode=useRef<HTMLDivElement>(null); const map=useRef<maplibregl.Map|null>(null); const marker=useRef<maplibregl.Marker|null>(null);
  const lat=Number(latitude), lng=Number(longitude), coordinatesValid=latitude.trim()!==""&&longitude.trim()!==""&&Number.isFinite(lat)&&lat>=-90&&lat<=90&&Number.isFinite(lng)&&lng>=-180&&lng<=180;
  useEffect(()=>{ if(!mapNode.current)return; const initialPosition:[number,number]=[initialLongitude,initialLatitude]; const instance=new maplibregl.Map({container:mapNode.current,style:{version:8,sources:{"gsi-pale":{type:"raster",tiles:["https://cyberjapandata.gsi.go.jp/xyz/pale/{z}/{x}/{y}.png"],tileSize:256,attribution:"地理院タイル"}},layers:[{id:"gsi-pale",type:"raster",source:"gsi-pale"}]},center:initialPosition,zoom:11}); const pin=new maplibregl.Marker({draggable:true}).setLngLat(initialPosition).addTo(instance); const sync=(p:maplibregl.LngLat)=>{setLongitude(String(p.lng));setLatitude(String(p.lat));}; pin.on("dragend",()=>sync(pin.getLngLat())); instance.on("click",(event)=>{pin.setLngLat(event.lngLat);sync(event.lngLat);}); map.current=instance;marker.current=pin;return()=>{instance.remove();map.current=null;marker.current=null;};},[initialLatitude,initialLongitude]);
  useEffect(()=>{if(coordinatesValid){marker.current?.setLngLat([lng,lat]);map.current?.easeTo({center:[lng,lat]});}},[coordinatesValid,lat,lng]);
  useEffect(()=>{const closeOnEscape=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!submitting){event.stopImmediatePropagation();onClose();}};document.addEventListener("keydown",closeOnEscape);return()=>document.removeEventListener("keydown",closeOnEscape);},[onClose,submitting]);
  const setDraft=(key:UserFishingSpotDetailItemKey, patch:Partial<SpotFieldObservationDraft>)=>setDrafts(current=>({...current,[key]:{...current[key],...patch}}));
  const applyCurrentLocation=async()=>{if(locationPending)return;setLocationPending(true);setLocationMessage(null);try{const location=await requestCurrentLocation();onCurrentLocationChange(location);setLatitude(String(location.latitude));setLongitude(String(location.longitude));map.current?.easeTo({center:[location.longitude,location.latitude],zoom:15});}catch(error){setLocationMessage(error instanceof Error?error.message:"現在地を取得できませんでした。手動で位置を指定できます。");}finally{setLocationPending(false);}};
  const submit=async()=>{if(submitting)return;if(!name.trim()){setError("地点名を入力してください。");return;}if(!coordinatesValid){setError("緯度は -90〜90、経度は -180〜180 の範囲で入力してください。");return;}setSubmitting(true);setError(null);try{const values=userFishingSpotDetailItemKeys.map(key=>buildUserSpotDetailInput(key,drafts[key])).filter((value):value is NonNullable<typeof value>=>value!==null);const spot=await createMyUserFishingSpotWithDetails(creationId.current,{name,latitude:lat,longitude:lng,areaName:areaName||null,spotType:spotType ? spotType as UserFishingSpot["spotType"] : null},values);onCreated(spot);}catch(error){console.error("地点登録に失敗しました",error);setError("地点を保存できませんでした。入力内容は保持されています。通信状態を確認してください。");}finally{setSubmitting(false);}};
  return <div className={styles.backdrop} onMouseDown={e=>{if(e.target===e.currentTarget&&!submitting)onClose();}}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="user-spot-title"><header className={styles.header}><h2 id="user-spot-title">地点登録</h2><button className={styles.close} type="button" aria-label="閉じる" disabled={submitting} onClick={onClose}>×</button></header><div className={styles.form}><div className={styles.grid}><label className={`${styles.field} ${styles.wide}`}>地点名（必須）<input maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label className={styles.field}>エリア（任意）<input maxLength={120} value={areaName} onChange={e=>setAreaName(e.target.value)}/></label><label className={styles.field}>地点種別（任意）<select value={spotType} onChange={e=>setSpotType(e.target.value)}><option value="">未入力</option>{userFishingSpotTypes.map(value=><option key={value}>{value}</option>)}</select></label></div><div><strong className={styles.sectionTitle}>位置（必須）</strong><p className={styles.hint}>地図をクリックするか、ピンを移動してください。座標欄からも変更できます。</p><div className={styles.locationRow}>{(locationPending||locationMessage)&&<span role="status">{locationPending?"現在地を取得中です":locationMessage}</span>}<button type="button" disabled={locationPending} aria-busy={locationPending} onClick={()=>void applyCurrentLocation()}>{locationPending&&<span className={styles.locationSpinner} aria-hidden="true"/>}現在地から登録</button></div><div className={styles.map} ref={mapNode}/></div><div className={styles.grid}><label className={styles.field}>緯度（-90〜90）<input inputMode="decimal" value={latitude} onChange={e=>setLatitude(e.target.value)}/></label><label className={styles.field}>経度（-180〜180）<input inputMode="decimal" value={longitude} onChange={e=>setLongitude(e.target.value)}/></label></div><DetailSection title="釣場情報" keys={fishingKeys} drafts={drafts} setDraft={setDraft}/><DetailSection title="地形情報" keys={terrainKeys} drafts={drafts} setDraft={setDraft}/>{error&&<p className={styles.error} role="alert">{error}</p>}<div className={styles.actions}><button className={styles.cancel} type="button" disabled={submitting} onClick={onClose}>キャンセル</button><button className={styles.save} type="button" disabled={submitting} onClick={()=>void submit()}>{submitting?"登録中…":"登録する"}</button></div></div></section></div>;
}

function DetailSection({title,keys,drafts,setDraft}:{title:string;keys:readonly UserFishingSpotDetailItemKey[];drafts:Record<UserFishingSpotDetailItemKey,SpotFieldObservationDraft>;setDraft:(key:UserFishingSpotDetailItemKey,patch:Partial<SpotFieldObservationDraft>)=>void}){return <details className={styles.details}><summary>{title}（任意）</summary><div className={styles.detailGrid}>{keys.map(key=><DetailInput key={key} itemKey={key} draft={drafts[key]} onChange={patch=>setDraft(key,patch)}/>)}</div></details>}
function DetailInput({itemKey,draft,onChange}:{itemKey:UserFishingSpotDetailItemKey;draft:SpotFieldObservationDraft;onChange:(patch:Partial<SpotFieldObservationDraft>)=>void}){const config=spotFieldObservationConfigs[itemKey];const label=labels.get(itemKey)??itemKey;const notice=config.safetyNotice?<p className={styles.safetyNotice}>{config.safetyNotice}</p>:null;if(config.kind==="multi")return <fieldset className={styles.field}><legend>{label}</legend>{notice}<div className={styles.checks}>{config.options?.map(option=><label className={styles.choice} key={option}><input type="checkbox" checked={draft.listValue.includes(option)} onChange={e=>onChange({listValue:e.target.checked?[...draft.listValue,option]:draft.listValue.filter(value=>value!==option)})}/>{option}</label>)}</div></fieldset>;if(config.kind==="single")return <label className={styles.field}>{label}{notice}<select value={draft.textValue} onChange={e=>onChange({textValue:e.target.value})}><option value="">未入力</option>{config.options?.map(option=><option key={option}>{option}</option>)}</select></label>;return <label className={styles.field}>{label}{notice}{config.kind==="number"?<input type="number" min="0" max="1000" step="any" value={draft.numberValue} onChange={e=>onChange({numberValue:e.target.value})}/>:<textarea maxLength={config.maxLength} placeholder={config.placeholder} value={draft.textValue} onChange={e=>onChange({textValue:e.target.value})}/>}<input type="hidden" value={draft.checkedAt||getTodayInJapan()} readOnly/></label>}
