import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const migration = await readFile("supabase/migrations/20260801120000_issue_396_private_record_photos.sql", "utf8");
const domain = await readFile("src/domain/recordPhoto.ts", "utf8");
const repository = await readFile("src/lib/recordPhotoRepository.ts", "utf8");
const catchUi = await readFile("src/components/ExternalCatchMemoSection.tsx", "utf8");
const reportUi = await readFile("src/components/UserSpotFieldReportSection.tsx", "utf8");
for (const value of ["private-record-photos", "create table public.record_photos", "record_photos_owner_select", "add_my_record_photo", "remove_my_record_photo", "delete linked storage objects first"]) assert.ok(migration.includes(value));
assert.match(migration, /sort_order between 0 and 2/);
assert.match(migration, /byte_size between 1 and 460800/);
assert.match(migration, /width between 1 and 1280/);
assert.match(migration, /owner_id = auth\.uid\(\)::text/g);
assert.doesNotMatch(migration, /insert into storage\.objects|delete from storage\.objects/i);
assert.match(domain, /20 \* 1024 \* 1024/);
assert.match(domain, /450 \* 1024/);
assert.match(domain, /canvasToWebp/);
assert.match(repository, /upsert: false/);
assert.match(repository, /storage\.from\(BUCKET\)\.remove/);
assert.match(repository, /isRecordPhotoBackendMissing/);
assert.match(catchUi, /targetType="catch_memo"/);
assert.match(reportUi, /targetType="field_report"/);
console.log("Issue #396 record photo checks passed.");
