import assert from "node:assert/strict";
import fs from "node:fs";
import { formatLocationAccuracy, geolocationErrorMessage } from "../src/domain/geolocation.ts";

const map = fs.readFileSync("src/components/FishingMap.tsx", "utf8");
const modal = fs.readFileSync("src/components/UserFishingSpotRegistrationModal.tsx", "utf8");
const mapStyles = fs.readFileSync("src/app/globals.css", "utf8");
const modalStyles = fs.readFileSync("src/components/UserFishingSpotRegistrationModal.module.css", "utf8");
const dashboard = fs.readFileSync("src/components/FishingDashboard.tsx", "utf8");
assert.match(map, /aria-label\", \"現在地を表示\"/, "the map location control has an accessible icon label");
assert.match(map, /currentLocationMapControl/, "the location icon is added to the existing MapLibre control column");
assert.match(map, /button\.title = "現在地を表示"/);
assert.match(mapStyles, /currentLocationMapControl[^}]*width: 44px; height: 44px;/, "the location icon has a touch-sized target");
assert.doesNotMatch(map, /className="currentLocationControl"/, "the standalone location row is removed");
assert.match(map, /currentLocationMarker/, "current location uses a dedicated marker");
assert.match(map, /easeTo\(\{ center: \[location\.longitude, location\.latitude\]/);
assert.match(modal, /現在地から登録<\/button>/, "registration button text stays fixed");
assert.doesNotMatch(modal, /現在地を再取得|現在地を使う|\?"取得中…"/, "registration button text does not change with state");
assert.match(modal, /styles\.locationRow/, "registration location actions remain in their position section");
assert.match(modalStyles, /locationRow\{[^}]*justify-content:flex-end/, "registration location actions are right aligned");
assert.match(modal, /const location=await requestCurrentLocation\(\)/, "registration always requests a fresh location");
assert.doesNotMatch(modal, /currentLocation\?\?await requestCurrentLocation/, "registration does not reuse a stale session location");
assert.match(modal, /setLatitude\(String\(location\.latitude\)\)/);
assert.match(modal, /setLongitude\(String\(location\.longitude\)\)/);
assert.match(modal, /draggable:true/);
assert.match(modal, /instance\.on\("click"/);
assert.match(dashboard, /currentLocation=\{currentLocation\}/, "session location is shared with registration");
assert.match(dashboard, /initialLongitude=\{environmentSpot\?\.longitude/, "registration receives a numeric initial longitude");
assert.match(modal, /\},\[initialLatitude,initialLongitude\]\);/, "registration map initialization uses stable numeric dependencies");
assert.doesNotMatch(dashboard, /initialPosition=\{\[/, "the dashboard does not pass a new position array on every render");
assert.doesNotMatch(map + modal, /localStorage|supabase/i, "displaying a location does not persist it");
assert.equal(formatLocationAccuracy(18.6), "推定精度 約19m");
assert.match(geolocationErrorMessage({ code: 1 }), /手動/);
assert.match(geolocationErrorMessage({ code: 3 }), /タイムアウト/);
console.log("Issue #394 current location checks passed");
