import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const migration = await readFile("supabase/migrations/20260801120000_issue_396_private_record_photos.sql", "utf8");
const domain = await readFile("src/domain/recordPhoto.ts", "utf8");
const repository = await readFile("src/lib/recordPhotoRepository.ts", "utf8");
const catchUi = await readFile("src/components/ExternalCatchMemoSection.tsx", "utf8");
const reportUi = await readFile("src/components/UserSpotFieldReportSection.tsx", "utf8");
for (const value of ["private-record-photos", "create table public.record_photos", "record_photos_owner_select", "add_my_record_photo", "remove_my_record_photo", "delete linked storage objects first"]) assert.ok(migration.includes(value));
assert.match(migration, /sort_order between 0 and 2/);
assert.match(migration, /byte_size between 1 and 460800/);
assert.match(migration, /width between 1 and 1280/);
assert.match(migration, /owner_id = auth\.uid\(\)::text/g);
assert.doesNotMatch(migration, /insert into storage\.objects|delete from storage\.objects/i);
assert.match(domain, /20 \* 1024 \* 1024/);
assert.match(domain, /450 \* 1024/);
assert.match(domain, /canvasToWebp/);
assert.match(repository, /upsert: false/);
assert.match(repository, /storage\.from\(BUCKET\)\.remove/);
assert.match(repository, /isRecordPhotoBackendMissing/);
assert.match(catchUi, /targetType="catch_memo"/);
assert.match(reportUi, /targetType="field_report"/);
console.log("Issue #396 record photo checks passed.");

// Review regression contract: retry keeps the saved target and removes completed batch items.
assert.match(catchUi, /savedMemoId !== null \|\| await onMemoSave/);
assert.match(reportUi, /savedReportId \?\? await state\.saveReport/);
assert.match(repository, /class RecordPhotoBatchError/);
assert.match(repository, /completedPhotoIds/);
assert.match(repository, /reconcileRecordPhotoObjects/);
assert.match(repository, /孤立写真を回収できませんでした/);
assert.match(repository, /cleanupError/);
assert.match(repository, /return photos;/); // stale metadata is retained without a signed URL
assert.doesNotMatch(repository, /return photos\.filter/);
assert.match(repository, /private-record-photos\|bucket not found/);
assert.match(migration, /can_write_my_record_photo_object/);
assert.match(migration, /array_length\(v_parts, 1\) <> 3/);
assert.match(migration, /\.webp\$'/);
assert.match(migration, /storage object size mismatch/);
assert.match(migration, /v_object_size <> p_byte_size/);
assert.match(migration, /created_by = 'authenticated_user'/);
assert.doesNotMatch(migration, /storage\.buckets \(id, name, public,/);
