import { readFileSync } from 'node:fs'; import { join } from 'node:path'; import { createRequire } from 'node:module'; import ts from 'typescript';
const req=createRequire(import.meta.url),cache=new Map();function load(p){if(cache.has(p))return cache.get(p).exports;const m={exports:{}};cache.set(p,m);const out=ts.transpileModule(readFileSync(join(process.cwd(),p),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;new Function('exports','require','module',out)(m.exports,s=>s.startsWith('@/')?load(`src/${s.slice(2)}.ts`):req(s),m);return m.exports}function ok(v,m){if(!v)throw new Error(m)}
const p=load('src/domain/scoreV2Production.ts'); const spot={id:'s',name:'港',areaName:'湾',latitude:0,longitude:0,spotType:'漁港',shoreAccess:'不明',targetSpecies:[],recommendedMethods:[],coordinatePrecision:'exact'};
const source={source:{id:'x',sourceType:'official',sourceName:'internal',sourceUrl:'https://example.test',checkedOn:'2026-01-01',note:'secret'},relation:'supporting',note:'secret'};
const value=(itemKey,valueTextList,confidence='high',overrides={})=>({id:itemKey,spotId:'s',itemKey,informationState:'has_evidence',valueText:null,valueTextList,valueNumber:null,valueBoolean:null,valueJson:null,unit:null,confidence,contributionOrigin:'curated_research',contributorId:null,submittedAt:null,moderationStatus:'not_required',reviewStatus:'reviewed',adoptionStatus:'adopted',note:'internal note',checkedAt:'2026-01-01',sources:[source],...overrides});
const details={itemDefinitions:[],values:[value('target_species',['アジ']),value('recommended_methods',['サビキ']),value('spot_features',['fishing_port']),value('coastal_topography',['open_sea'],'medium'),value('bottom_material',['rocky'],'medium'),value('shore_access',['stable'],'medium')]};
const weather=(windSpeedKmh=10.8)=>({temperatureCelsius:20,weatherCode:0,weatherLabel:'晴れ',precipitationMm:0,precipitationProbabilityPercent:0,windSpeedKmh,windDirectionDegrees:0,windDirectionLabel:'北',windGustKmh:20,observedAt:'2026-07-20T06:00'}); const marine=(height,temp=22,wave=.3)=>({seaSurfaceTemperatureCelsius:temp,seaLevelHeightMslMeters:height,waveHeightMeters:wave,waveDirectionDegrees:0,waveDirectionLabel:'北',wavePeriodSeconds:5,oceanCurrentVelocityKmh:1,oceanCurrentDirectionDegrees:0,oceanCurrentDirectionLabel:'北',observedAt:'2026-07-20T06:00'});
const env={point:{spotId:'s',spotName:'港',latitude:0,longitude:0},hourly:[{forecastTime:'2026-07-20T05:00',weather:null,marine:marine(0)},{forecastTime:'2026-07-20T06:00',weather:weather(),marine:marine(1)},{forecastTime:'2026-07-20T07:00',weather:null,marine:marine(.5)}],dailySun:[{date:'2026-07-20',sunrise:'2026-07-20T05:30',sunset:'2026-07-20T19:30'}],weatherAvailable:true,marineAvailable:true,fetchedAt:'2026-07-20T00:00Z',sourceName:'Open-Meteo',sourceUrl:'https://open-meteo.com',cacheStatus:'fresh',fetchStatus:'success',warning:null,tideReference:{spotId:'s',referenceName:null,url:'x',note:'x'}};
const input=p.buildScoreV2SpeciesInput({species:'アジ',spot,details,environment:env,selectedDateTime:'2026-07-20T06:00'});ok(input.spotEvidence.directSpecies.score===100,'approved species');ok(input.spotEvidence.habitat!==null,'habitat');ok(input.environmentEvidence.waterTemperature.score===100,'temperature');ok(input.environmentEvidence.tideCurrent.score===70,'tide');ok(input.environmentEvidence.windWave.score===90,'wind boundary');ok(input.environmentEvidence.seasonTime.score===100,'morning');
const rejected={...details,values:[value('target_species',['アジ'],'high',{adoptionStatus:'not_adopted'})]};ok(p.buildScoreV2SpeciesInput({species:'アジ',spot,details:rejected,selectedDateTime:'2026-07-20T06:00'}).spotEvidence.directSpecies===null,'rejected null');ok(p.buildScoreV2SpeciesInput({species:'サバ',spot,details,environment:env,selectedDateTime:'2026-07-20T06:00'}).environmentEvidence===undefined,'unsupported');ok(Object.keys(p.SCORE_V2_METHOD_COMPATIBILITY).length===7,'methods');ok(p.buildMethodSpotSuitability(details,'サビキ').score===100,'suitability');
for(const [field,n,reason] of [['windSpeedKmh',36,'強風'],['windGustKmh',72,'突風'],['precipitationMm',30,'大雨'],['weatherCode',95,'雷雨']]){const e=structuredClone(env);e.hourly[1].weather[field]=n;const r=p.calculateProductionScoreV2({spot,details,environment:e,selectedDateTime:'2026-07-20T06:00'});ok(r.status==='unsafe'&&r.unsafeReasons.includes(reason)&&r.speciesResults.every(x=>x.overallScore===null),reason)}const e=structuredClone(env);e.hourly[1].marine.waveHeightMeters=1.25;ok(p.calculateProductionScoreV2({spot,details,environment:e,selectedDateTime:'2026-07-20T06:00'}).status==='unsafe','wave');
const stale={...env,cacheStatus:'cache-stale'};ok(p.buildScoreV2SpeciesInput({species:'アジ',spot,details,environment:stale,selectedDateTime:'2026-07-20T06:00'}).environmentEvidence.waterTemperature===null,'stale');ok(p.buildScoreV2SpeciesInput({species:'アジ',spot,details,environment:env,selectedDateTime:'2026-07-20T08:00'}).environmentEvidence.waterTemperature===null,'exact row');const partial=structuredClone(env);partial.hourly[1].marine.waveHeightMeters=null;partial.hourly[1].weather.windGustKmh=null;ok(p.buildScoreV2SpeciesInput({species:'アジ',spot,details,environment:partial,selectedDateTime:'2026-07-20T06:00'}).environmentEvidence.windWave.score===90,'partial');ok(!JSON.stringify(input).includes('internal note')&&!JSON.stringify(input).includes('example.test'),'metadata');console.log('SCORE v2 production checks passed.');
