import { readFileSync } from 'node:fs'; import { dirname, extname, join, normalize } from 'node:path'; import { createRequire } from 'node:module'; import ts from 'typescript';
const req=createRequire(import.meta.url),cache=new Map();function load(p){if(cache.has(p))return cache.get(p).exports;const m={exports:{}};cache.set(p,m);const out=ts.transpileModule(readFileSync(join(process.cwd(),p),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true,resolveJsonModule:true}}).outputText;new Function('exports','require','module',out)(m.exports,s=>{if(s.startsWith('@/'))return load(`src/${s.slice(2)}.ts`);if(s.startsWith('.')){const resolved=normalize(join(dirname(p),s));return extname(resolved)==='.json'?req(join(process.cwd(),resolved)):load(extname(resolved)?resolved:`${resolved}.ts`)}return req(s)},m);return m.exports}function ok(v,m){if(!v)throw new Error(m)}
const p=load('src/domain/scoreV2Production.ts'); const {fishingSpots}=load('src/data/fishingSpots.ts'); const {getStaticFishingSpotDetails}=load('src/lib/fishingSpotDetailRepository.ts'); const spot={id:'s',name:'港',areaName:'湾',latitude:0,longitude:0,spotType:'漁港',shoreAccess:'不明',targetSpecies:[],recommendedMethods:[],coordinatePrecision:'exact'};
const source={source:{id:'x',sourceType:'official',sourceName:'internal',sourceUrl:'https://example.test',checkedOn:'2026-01-01',note:'secret'},relation:'supporting',note:'secret'};
const value=(itemKey,valueTextList,confidence='high',overrides={})=>({id:itemKey,spotId:'s',itemKey,informationState:'has_evidence',valueText:null,valueTextList,valueNumber:null,valueBoolean:null,valueJson:null,unit:null,confidence,contributionOrigin:'curated_research',contributorId:null,submittedAt:null,moderationStatus:'not_required',reviewStatus:'reviewed',adoptionStatus:'adopted',note:'internal note',checkedAt:'2026-01-01',sources:[source],...overrides});
const details={itemDefinitions:[],values:[value('target_species',['アジ']),value('recommended_methods',['サビキ']),value('spot_features',['fishing_port']),value('coastal_topography',['open_sea'],'medium'),value('bottom_material',['rocky'],'medium'),value('shore_access',['stable'],'medium')]};
const weather=(windSpeedKmh=10.8)=>({temperatureCelsius:20,weatherCode:0,weatherLabel:'晴れ',precipitationMm:0,precipitationProbabilityPercent:0,windSpeedKmh,windDirectionDegrees:0,windDirectionLabel:'北',windGustKmh:20,observedAt:'2026-07-20T06:00'}); const marine=(height,temp=22,wave=.3)=>({seaSurfaceTemperatureCelsius:temp,seaLevelHeightMslMeters:height,waveHeightMeters:wave,waveDirectionDegrees:0,waveDirectionLabel:'北',wavePeriodSeconds:5,oceanCurrentVelocityKmh:1,oceanCurrentDirectionDegrees:0,oceanCurrentDirectionLabel:'北',observedAt:'2026-07-20T06:00'});
const env={point:{spotId:'s',spotName:'港',latitude:0,longitude:0},hourly:[{forecastTime:'2026-07-20T05:00',weather:null,marine:marine(0)},{forecastTime:'2026-07-20T06:00',weather:weather(),marine:marine(1)},{forecastTime:'2026-07-20T07:00',weather:null,marine:marine(.5)}],dailySun:[{date:'2026-07-20',sunrise:'2026-07-20T05:30',sunset:'2026-07-20T19:30'}],weatherAvailable:true,marineAvailable:true,fetchedAt:'2026-07-20T00:00Z',sourceName:'Open-Meteo',sourceUrl:'https://open-meteo.com',cacheStatus:'fresh',fetchStatus:'success',warning:null,tideReference:{spotId:'s',referenceName:null,url:'x',note:'x'}};
const input=p.buildScoreV2SpeciesInput({species:'アジ',spot,details,environment:env,selectedDateTime:'2026-07-20T06:00'});ok(input.spotEvidence.directSpecies.score===100,'approved species');ok(input.spotEvidence.habitat!==null,'habitat');ok(input.environmentEvidence.waterTemperature.score===100,'temperature');ok(input.environmentEvidence.tideCurrent.score===70,'tide');ok(input.environmentEvidence.windWave.score===90,'wind boundary');ok(input.environmentEvidence.seasonTime.score===100,'morning');
const rejected={...details,values:[value('target_species',['アジ'],'high',{adoptionStatus:'not_adopted'})]};ok(p.buildScoreV2SpeciesInput({species:'アジ',spot,details:rejected,selectedDateTime:'2026-07-20T06:00'}).spotEvidence.directSpecies===null,'rejected null');ok(p.buildScoreV2SpeciesInput({species:'サバ',spot,details,environment:env,selectedDateTime:'2026-07-20T06:00'}).environmentEvidence===undefined,'unsupported');ok(Object.keys(p.SCORE_V2_METHOD_COMPATIBILITY).length===7,'methods');ok(p.buildMethodSpotSuitability(details,'サビキ').score===94,'55/30/15 suitability ignores recommended_methods shortcut');
const wrongSpotDetails={...details,values:details.values.map(item=>({...item,spotId:'another-spot'}))};const wrongSpotResult=p.calculateProductionScoreV2({spot,details:wrongSpotDetails,environment:null,selectedDateTime:'2026-07-20T06:00'});ok(wrongSpotResult.status==='safety_unknown','missing environment keeps a result');ok(wrongSpotResult.speciesResults.every(item=>item.overallScore===null),'missing environment never calculates overall scores');ok(wrongSpotResult.speciesResults.find(item=>item.species==='アジ').spotCompatibilityScore===null,'details from another spot are excluded from species scoring');ok(wrongSpotResult.methodResults.every(item=>item.spotSuitabilityScore===null),'details from another spot are excluded from method scoring');
const noEnvironmentResult=p.calculateProductionScoreV2({spot,details,environment:null,selectedDateTime:'2026-07-20T06:00'});ok(noEnvironmentResult.speciesResults.find(item=>item.species==='アジ').spotCompatibilityScore!==null,'zero forecast rows retain the spot compatibility reference score');ok(noEnvironmentResult.speciesResults.every(item=>item.overallScore===null),'zero forecast rows keep every overall score null');
for(const [field,n,reason] of [['windSpeedKmh',36,'強風'],['windGustKmh',72,'突風'],['precipitationMm',30,'大雨'],['weatherCode',95,'雷雨']]){const e=structuredClone(env);e.hourly[1].weather[field]=n;const r=p.calculateProductionScoreV2({spot,details,environment:e,selectedDateTime:'2026-07-20T06:00'});ok(r.status==='unsafe'&&r.unsafeReasons.includes(reason)&&r.speciesResults.every(x=>x.overallScore===null),reason)}const e=structuredClone(env);e.hourly[1].marine.waveHeightMeters=1.25;ok(p.calculateProductionScoreV2({spot,details,environment:e,selectedDateTime:'2026-07-20T06:00'}).status==='unsafe','wave');
const symmetricHigh=structuredClone(env);symmetricHigh.hourly[2].marine.seaLevelHeightMslMeters=0;ok(p.buildScoreV2SpeciesInput({species:'アジ',spot,details,environment:symmetricHigh,selectedDateTime:'2026-07-20T06:00'}).environmentEvidence.tideCurrent.score===70,'symmetric high tide');const symmetricLow=structuredClone(env);symmetricLow.hourly[0].marine.seaLevelHeightMslMeters=1;symmetricLow.hourly[1].marine.seaLevelHeightMslMeters=0;symmetricLow.hourly[2].marine.seaLevelHeightMslMeters=1;ok(p.buildScoreV2SpeciesInput({species:'アジ',spot,details,environment:symmetricLow,selectedDateTime:'2026-07-20T06:00'}).environmentEvidence.tideCurrent.score===60,'symmetric low tide');
const temperatureCases={アジ:[[9,40],[15,60],[18,80],[22,100],[26,100],[28,80],[30,60],[32,40]],シーバス:[[6,40],[12,60],[17,80],[21,100],[27,100],[30,40],[33,20]],チヌ:[[10,40],[15,60],[20,80],[23,100],[29,100],[32,60],[35,40]]};for(const [species,cases] of Object.entries(temperatureCases)){for(const [temperature,expected] of cases){const e=structuredClone(env);e.hourly[1].marine.seaSurfaceTemperatureCelsius=temperature;ok(p.buildScoreV2SpeciesInput({species,spot,details,environment:e,selectedDateTime:'2026-07-20T06:00'}).environmentEvidence.waterTemperature.score===expected,`${species} temperature ${temperature}`)}}
const unsupported=['サバ','イワシ','青物','シイラ','ヒラメ','マゴチ','アオリイカ','ヤリイカ','コウイカ','真鯛','キス','根魚'];const all=p.calculateProductionScoreV2({spot,details,environment:env,selectedDateTime:'2026-07-20T06:00'});for(const species of unsupported)ok(all.speciesResults.find(x=>x.species===species).informationStatus==='no_information',`${species} no_information`);
const expectedCompatibility={ジギング:2,キャスティング:3,コマセ:2,泳がせ:1,サビキ:1,エギング:0,その他:0};for(const [method,count] of Object.entries(expectedCompatibility)){ok(p.SCORE_V2_METHOD_COMPATIBILITY[method].length===count,`${method} compatibility count`);const result=all.methodResults.find(x=>x.method===method);ok(result.contributingSpeciesCount<=3,`${method} uses at most top three species`);if(result.speciesAverageScore!==null){const scores=all.speciesResults.filter(x=>p.SCORE_V2_METHOD_COMPATIBILITY[method].includes(x.species)&&x.overallScore!==null).map(x=>x.overallScore).sort((a,b)=>b-a).slice(0,3);ok(result.speciesAverageScore===Math.round(scores.reduce((sum,x)=>sum+x,0)/scores.length),`${method} top three average`)}}
const stale={...env,cacheStatus:'cache-stale'};ok(p.buildScoreV2SpeciesInput({species:'アジ',spot,details,environment:stale,selectedDateTime:'2026-07-20T06:00'}).environmentEvidence.waterTemperature===null,'stale');ok(p.calculateProductionScoreV2({spot,details,environment:stale,selectedDateTime:'2026-07-20T06:00'}).safetyStatus==='unknown','stale safety unknown');ok(p.buildScoreV2SpeciesInput({species:'アジ',spot,details,environment:env,selectedDateTime:'2026-07-20T08:00'}).environmentEvidence.waterTemperature===null,'exact row');ok(p.calculateProductionScoreV2({spot,details,environment:env,selectedDateTime:'2026-07-20T08:00'}).safetyStatus==='unknown','missing selected row safety unknown');const missingSafety=structuredClone(env);for(const key of ['windSpeedKmh','windGustKmh','precipitationMm','weatherCode'])missingSafety.hourly[1].weather[key]=null;missingSafety.hourly[1].marine.waveHeightMeters=null;const unknown=p.calculateProductionScoreV2({spot,details,environment:missingSafety,selectedDateTime:'2026-07-20T06:00'});ok(unknown.status==='safety_unknown'&&unknown.speciesResults.every(x=>x.overallScore===null),'all safety values missing');const partial=structuredClone(env);partial.hourly[1].marine.waveHeightMeters=null;partial.hourly[1].weather.windGustKmh=null;ok(p.buildScoreV2SpeciesInput({species:'アジ',spot,details,environment:partial,selectedDateTime:'2026-07-20T06:00'}).environmentEvidence.windWave.score===90,'partial');ok(p.calculateProductionScoreV2({spot,details,environment:partial,selectedDateTime:'2026-07-20T06:00'}).safetyStatus==='unknown','partial safety unknown');ok(!JSON.stringify(input).includes('internal note')&&!JSON.stringify(input).includes('example.test'),'metadata');

ok(fishingSpots.length===18,'18 production spots');
const forbiddenMetadataKeys=new Set(['source','sources','sourceUrl','sourceName','note','internalNote','internal_note']);
function hasForbiddenMetadata(value){if(Array.isArray(value))return value.some(hasForbiddenMetadata);if(!value||typeof value!=='object')return false;return Object.entries(value).some(([key,nested])=>forbiddenMetadataKeys.has(key)||hasForbiddenMetadata(nested))}
let spotsWithApprovedScoreEvidence=0;
for(const productionSpot of fishingSpots){
  const productionDetails=getStaticFishingSpotDetails(productionSpot.id);
  ok(productionDetails.values.length>0,`${productionSpot.id} has adopted production details`);
  ok(productionDetails.values.every(detail=>detail.spotId===productionSpot.id),`${productionSpot.id} details are scoped to the requested spot`);
  const productionEnvironment=structuredClone(env);
  productionEnvironment.point={spotId:productionSpot.id,spotName:productionSpot.name,latitude:productionSpot.latitude,longitude:productionSpot.longitude};
  const result=p.calculateProductionScoreV2({spot:productionSpot,details:productionDetails,environment:productionEnvironment,selectedDateTime:'2026-07-20T06:00'});
  const supportedInputs=['アジ','シーバス','チヌ'].map(species=>p.buildScoreV2SpeciesInput({species,spot:productionSpot,details:productionDetails,environment:productionEnvironment,selectedDateTime:'2026-07-20T06:00'}));
  const usesApprovedDetail=supportedInputs.some(speciesInput=>['directSpecies','habitat','methodAffinity'].some(key=>speciesInput.spotEvidence[key]!==null))||result.methodResults.some(method=>method.spotSuitabilityScore!==null);
  if(usesApprovedDetail)spotsWithApprovedScoreEvidence+=1;
  for(const species of unsupported)ok(result.speciesResults.find(item=>item.species===species)?.informationStatus==='no_information',`${productionSpot.id} ${species} no_information`);
  ok(!hasForbiddenMetadata(result.speciesResults),`${productionSpot.id} species results exclude internal metadata`);
  ok(!hasForbiddenMetadata(result.methodResults),`${productionSpot.id} method results exclude internal metadata`);
  ok(!hasForbiddenMetadata(result.speciesResults.flatMap(item=>item.reasons)),`${productionSpot.id} species display reasons exclude internal metadata`);
  ok(!hasForbiddenMetadata(result.methodResults.flatMap(item=>item.reasons)),`${productionSpot.id} method display reasons exclude internal metadata`);
}
ok(spotsWithApprovedScoreEvidence>0,'qualifying adopted values generate production score evidence instead of uniform zeroes');
const changingEnvironment=structuredClone(env);changingEnvironment.hourly[2]={forecastTime:'2026-07-20T07:00',weather:weather(5),marine:marine(.5,28,.9)};changingEnvironment.hourly.push({forecastTime:'2026-07-20T08:00',weather:weather(5),marine:marine(0,28,.9)});const selectedAtSix=p.buildScoreV2SpeciesInput({species:'アジ',spot,details,environment:changingEnvironment,selectedDateTime:'2026-07-20T06:00'});const selectedAtSeven=p.buildScoreV2SpeciesInput({species:'アジ',spot,details,environment:changingEnvironment,selectedDateTime:'2026-07-20T07:00'});ok(selectedAtSix.environmentEvidence.waterTemperature.score!==selectedAtSeven.environmentEvidence.waterTemperature.score,'selected row changes water-temperature input');ok(selectedAtSix.environmentEvidence.tideCurrent.score!==selectedAtSeven.environmentEvidence.tideCurrent.score,'selected row changes tide input');ok(selectedAtSix.environmentEvidence.windWave.score!==selectedAtSeven.environmentEvidence.windWave.score,'selected row changes wind/wave input');ok(selectedAtSix.environmentEvidence.seasonTime.score!==selectedAtSeven.environmentEvidence.seasonTime.score,'selected row changes time-of-day input');
console.log('SCORE v2 production checks passed.');
